### ISSUE TITLE
用户安装教程可不可以详细一点些？

### ISSUE THREAD

**Issue by ZLBusyBoy** [xaecbd/RCT#1]
比如用户如何直接在linux上安装，开头就是  java -jar RCT-Dashboard-2.0.0.jar，但是这个jar包咋来的？

**Comment by TrumanDu** [comment]
@ZLBusyBoy 好的，我们会修改，以便更容易使用

**Comment by TrumanDu** [comment]
@ZLBusyBoy 已经修改，如有问题，欢迎再提出来
