### ISSUE TITLE
分析rdb文件报错

### ISSUE THREAD

**Issue by zeusYi** [xaecbd/RCT#28]
10.249.201.87 analyzeInstance inactive!
analyze job just parse one of slaves rdb file in all masters .

**Comment by TrumanDu** [comment]
@yiwenshuo 10.249.201.87这个节点上有部署分析器么？

**Comment by zeusYi** [comment]
两个jar包都部署 并且启动了，

**Comment by TrumanDu** [comment]
RCT-Analyze 启动起来有没有报错？查看一下 RCT-Dashboard http:xxx.xx.xx.xx:8080/eureka-ui
