### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by pengai** [xaecbd/RCT#32]
hi:
My environment is:
master: 192.168.1.x: 6379
slave: 192.168.1.y: 6379
One master and one slave.
According to your deployment document, execute the jar package without making any changes to the application.properties file. Manually performing analysis always reports the following error:
analyze job just parse one of slaves rdb file in all masters .

![图片](https://user-images.githubusercontent.com/18377019/71608905-5d29f480-2bbf-11ea-8de2-dcf1c88c4703.png)
Ask you: Is there anything wrong with the setting?
There is also a problem with the Data Path configuration path. For example, my dump.rdb file path is: /var/lib/redis/dump.rdb Why can't I write / var / lib / redis, the prompt is to / var / lib / redis Looking under the / 6379 / directory?

**Comment by TrumanDu** [comment]
@pengai 
>Ask you: Is there anything wrong with the setting?
There is also a problem with the Data Path configuration path. For example, my dump.rdb file path is: /var/lib/redis/dump.rdb Why can't I write / var / lib / redis, the prompt is to / var / lib / redis Looking under the / 6379 / directory?

yeah,Data Path configuration path must be {...}/ {...}/{port}/dump.rdb

**you redis not cluster mode**?

**Comment by pengai** [comment]
hi:
My environment is:
master: 192.168.1.x: 6379
slave: 192.168.1.y: 6379
One master and one slave. must be cluster mode?  
RCT-Dashboard

**Comment by pengai** [comment]
hi:
My Lab  environment is:
master: 192.168.1.x: 6379
slave: 192.168.1.y: 6379
One master and one slave. 

Does your project must be clustered mode? master-slave model possible?
There is another question:
Do the configuration items of RCT-Dashboard and RCT-Analyze use the defaults? I see that there is a configuration file application.properties: 
eureka.client.serviceUrl.defaultZone = http: // localhost: 8080 / eureka / 
Is this also the default setting?
Can you send me your WeChat or QQ number? I have several questions about the RCT project. My QQ number is 835221922.

**Comment by pengai** [comment]
hi  
问个关于Schedule：cron 表达式 的详细填写方式
我的写法:   50 11 * * *
![图片](https://user-images.githubusercontent.com/18377019/71811422-9aa2ec00-30af-11ea-8af8-b064d551e3a1.png)

当指定的时间点没有执行，这个cron是否和Linux的crontab的写法一致？我看你的git的文档对应的内容也没详细说明，它的这个Schedule正确的写法是如何？
![图片](https://user-images.githubusercontent.com/18377019/71811582-0c7b3580-30b0-11ea-84b4-34f014f0a867.png)

**Comment by TrumanDu** [comment]
@pengai **配置需要修改的**，毕竟是通过eureka 注册到中心节点（RCT-Dashboard）cron和linux不同，如果没有后方没有提示，证明你写错了。quartz-scheduler 建议使用[工具](http://cron.qqe2.com/)
